---
- name: Create a new host or update an existing host's info
  hosts: localhost
  connection: local
  #module: community.zabbix.zabbix_host
  server_url: https://dzbx1dsm.ad.mdp.com
  login_user: parza
  login_password: Ph@ni/cmt105
  host:
    hostname: chi-133-r6004c
    group
  template_name: TPL Printer SNMP Ricoh
  description: adding template to host
  host_groups: EI/Printers/Publishing/Chicago
  # - [CHI_Printers]
  link_templates:
    - Template Module Generic SNMPv2
    - TPL Module ICMP Ping
  status: enabled
  state: present
  inventory_mode: manual
  inventory_zabbix:
    tag: "{{ Device:Ricoh Printer}}"
  interfaces:
    - type: SNMP
      #ip: 10.216.2.158,10.216.2.89,10.216.2.111,10.216.2.188
      dns: "ad.mdp.com"
      port: "161"
      SNMP version: SNMPv2
      SNMP community: public
